apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "ryoshigademoapi"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "ryoshigademoapi"
    spec:
      containers:
        - name: "ryoshigademoapi"
          image: "ryoshiga.azurecr.io/ryoshigademoapi"
          ports:
          - containerPort: 80