# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_FUNCTIONAPP_NAME: ryoshiga  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './RYoshiga.Demo.FunctionApp/'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.101'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: ryoshiga.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build
      run:  docker build . -t ryoshiga.azurecr.io/ryoshigademoapi:${{ github.sha }}
    
    - name: Publish
      run:  docker push ryoshiga.azurecr.io/ryoshigademoapi:${{ github.sha }}

    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'ryoshiga-demo-api'
        images: 'ryoshiga.azurecr.io/ryoshigademoapi:${{ github.sha }}'
    
    - name: Azure logout
      run: az logout