# This is a basic workflow to help you get started with Actions

name: Provisioning

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - './Provisioning/**'
  pull_request:
    branches: [ master ]

env:
  AZURE_FUNCTIONAPP_NAME: ryoshiga  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './RYoshiga.Demo.FunctionApp/'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.101'              # set this to the dotnet version to use

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create resource group
      run: az group create --name ryoshiga-demo --location "UK West"
    
    - name: Test template
      run:  az deployment group validate --resource-group ryoshiga-demo --template-file ./Provisioning/template.json --parameters ./Provisioning/parameters.json
    
    - name: Deploy template
      run:  az deployment group create --resource-group ryoshiga-demo --template-file ./Provisioning/template.json --parameters ./Provisioning/parameters.json

    - name: Azure logout
      run: az logout